name: Python package

on:
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ]

  schedule:
    - cron: "0/3 * * * * "
    
permissions: 
    contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.x"]

    steps:
    - uses: actions/checkout@v4
      with: 
        token: ${{ secrets.ACTIONS_PAT }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
  

    - name: Run Python script to update CSV
      run: |
        python dataGenerator.py

  
    # - name: Set up Git repository 
    #   env: 
    #     ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }} 
    #   run: | 
    #     git init 
    #     git remote add origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/Swadeep888/DayTracking.git 
    # - name: Pull latest changes 
    #   env: 
    #       ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }} 
    #   run: | 
    #       git pull https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/Swadeep888/DayTracking.git main 
          

    - name: Commit and push changes
      env: 
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name "Swadeep888"
        git config --global user.email "swa.deep@outlook.com"
        # git remote add origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/Swadeep888/DayTracking.git
        # git pull https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/Swadeep888/DayTracking.git main
        dir 
        git add *.csv
        git commit -m "Update CSV file with new data"
        git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/Swadeep888/DayTracking.git main
