name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.x"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      run: |
        pytest

    - name: Run Python script to update CSV
      run: |
        python path/to/your/script.py

    - name: Commit and push changes
      run: |
        git config --global user.name "Swadeep888"
        git config --global user.email "swa.deep@outlook.com"
        dir 
        git add *.csv
        git commit -m "Update CSV file with new data"
        git push origin main
